# Generated by Django 2.1.2 on 2018-11-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='pj_participant1',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pj_participant2',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pj_participant3',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员3'),
        ),
    ]
