# Generated by Django 2.1.2 on 2018-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181118_0802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': '项目加分', 'verbose_name_plural': '项目'},
        ),
    ]
