# Generated by Django 2.1.2 on 2018-11-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('score_year_month', models.CharField(max_length=200, verbose_name='年月')),
                ('score_posts', models.FloatField(default=0.0, verbose_name='项目分数')),
                ('score_orders', models.FloatField(default=0.0, verbose_name='工单分数')),
                ('score_cutovers', models.FloatField(default=0.0, verbose_name='割接分数')),
                ('score_bonuses', models.FloatField(default=0.0, verbose_name='特殊加分')),
            ],
            options={
                'verbose_name': '总分排名',
                'verbose_name_plural': '总分',
            },
        ),
    ]
