# Generated by Django 2.1.2 on 2018-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scores',
            name='score_faulty',
            field=models.FloatField(default=0.0, verbose_name='故障分数'),
        ),
        migrations.AddField(
            model_name='scores',
            name='score_routine',
            field=models.FloatField(default=0.0, verbose_name='日常分数'),
        ),
    ]
