# Generated by Django 2.1.2 on 2020-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20181225_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('weiguorui', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('zhangchen', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('yuqiusi', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('liufeng', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('changxiaobo', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('suju', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('guoshaochuan', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('huoxiaoge', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('lixiaoxin', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('liujiang', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('chenlidong', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('suweiheng', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('yangxiao', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('liulei', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('huangqiangxu', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('wangzhiwu', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
            ],
            options={
                'verbose_name': '总分排名',
                'verbose_name_plural': '总分',
            },
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={},
        ),
    ]
