# Generated by Django 2.1.2 on 2020-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_auto_20181225_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attitude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('workeru', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workera', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerx', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerk', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerd', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerr', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerh', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerj', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workern', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerl', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerb', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workers', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerw', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workerm', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workeri', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workert', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
            ],
            options={
                'verbose_name': '总分排名',
                'verbose_name_plural': '总分',
            },
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={},
        ),
    ]
