# Generated by Django 2.1.2 on 2020-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20200406_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('weiguorui', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('zhangchen', models.FloatField(default=0.0, verbose_name='张晨分数')),
                ('yuqiusi', models.FloatField(default=0.0, verbose_name='于秋思分数')),
                ('liufeng', models.FloatField(default=0.0, verbose_name='刘峰分数')),
                ('changxiaobo', models.FloatField(default=0.0, verbose_name='常晓波分数')),
                ('suju', models.FloatField(default=0.0, verbose_name='苏飓分数')),
                ('guoshaochuan', models.FloatField(default=0.0, verbose_name='郭少钏分数')),
                ('huoxiaoge', models.FloatField(default=0.0, verbose_name='霍晓歌分数')),
                ('lixiaoxin', models.FloatField(default=0.0, verbose_name='李晓昕分数')),
                ('liujiang', models.FloatField(default=0.0, verbose_name='刘江分数')),
                ('chenlidong', models.FloatField(default=0.0, verbose_name='陈立栋分数')),
                ('suweiheng', models.FloatField(default=0.0, verbose_name='苏威衡分数')),
                ('yangxiao', models.FloatField(default=0.0, verbose_name='杨晓分数')),
                ('liulei', models.FloatField(default=0.0, verbose_name='刘雷分数')),
                ('huangqiangxu', models.FloatField(default=0.0, verbose_name='黄锵栩分数')),
                ('wangzhiwu', models.FloatField(default=0.0, verbose_name='汪志武分数')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('weiguorui', models.FloatField(default=0.0, verbose_name='韦国锐分数')),
                ('zhangchen', models.FloatField(default=0.0, verbose_name='张晨分数')),
                ('yuqiusi', models.FloatField(default=0.0, verbose_name='于秋思分数')),
                ('liufeng', models.FloatField(default=0.0, verbose_name='刘峰分数')),
                ('changxiaobo', models.FloatField(default=0.0, verbose_name='常晓波分数')),
                ('suju', models.FloatField(default=0.0, verbose_name='苏飓分数')),
                ('guoshaochuan', models.FloatField(default=0.0, verbose_name='郭少钏分数')),
                ('huoxiaoge', models.FloatField(default=0.0, verbose_name='霍晓歌分数')),
                ('lixiaoxin', models.FloatField(default=0.0, verbose_name='李晓昕分数')),
                ('liujiang', models.FloatField(default=0.0, verbose_name='刘江分数')),
                ('chenlidong', models.FloatField(default=0.0, verbose_name='陈立栋分数')),
                ('suweiheng', models.FloatField(default=0.0, verbose_name='苏威衡分数')),
                ('yangxiao', models.FloatField(default=0.0, verbose_name='杨晓分数')),
                ('liulei', models.FloatField(default=0.0, verbose_name='刘雷分数')),
                ('huangqiangxu', models.FloatField(default=0.0, verbose_name='黄锵栩分数')),
                ('wangzhiwu', models.FloatField(default=0.0, verbose_name='汪志武分数')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attitude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': '总分排名', 'verbose_name_plural': '总分'},
        ),
        migrations.AlterField(
            model_name='attitude',
            name='changxiaobo',
            field=models.FloatField(default=0.0, verbose_name='常晓波分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='chenlidong',
            field=models.FloatField(default=0.0, verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='guoshaochuan',
            field=models.FloatField(default=0.0, verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='huangqiangxu',
            field=models.FloatField(default=0.0, verbose_name='黄锵栩分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='huoxiaoge',
            field=models.FloatField(default=0.0, verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='liufeng',
            field=models.FloatField(default=0.0, verbose_name='刘峰分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='liujiang',
            field=models.FloatField(default=0.0, verbose_name='刘江分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='liulei',
            field=models.FloatField(default=0.0, verbose_name='刘雷分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='lixiaoxin',
            field=models.FloatField(default=0.0, verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='suju',
            field=models.FloatField(default=0.0, verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='suweiheng',
            field=models.FloatField(default=0.0, verbose_name='苏威衡分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='wangzhiwu',
            field=models.FloatField(default=0.0, verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='yangxiao',
            field=models.FloatField(default=0.0, verbose_name='杨晓分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='yuqiusi',
            field=models.FloatField(default=0.0, verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='zhangchen',
            field=models.FloatField(default=0.0, verbose_name='张晨分数'),
        ),
    ]
