# Generated by Django 2.1.2 on 2020-04-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20200406_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('workeru', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workera', models.FloatField(default=0.0, verbose_name='测试员工12分数')),
                ('workerx', models.FloatField(default=0.0, verbose_name='测试员工15分数')),
                ('workerk', models.FloatField(default=0.0, verbose_name='员工K分数')),
                ('workerd', models.FloatField(default=0.0, verbose_name='员工D分数')),
                ('workerr', models.FloatField(default=0.0, verbose_name='员工R分数')),
                ('workerh', models.FloatField(default=0.0, verbose_name='测试员工16分数')),
                ('workerj', models.FloatField(default=0.0, verbose_name='测试员工9分数')),
                ('workern', models.FloatField(default=0.0, verbose_name='测试员工2分数')),
                ('workerl', models.FloatField(default=0.0, verbose_name='员工L分数')),
                ('workerb', models.FloatField(default=0.0, verbose_name='测试员工13分数')),
                ('workers', models.FloatField(default=0.0, verbose_name='员工S分数')),
                ('workerw', models.FloatField(default=0.0, verbose_name='员工W分数')),
                ('workerm', models.FloatField(default=0.0, verbose_name='员工M分数')),
                ('workeri', models.FloatField(default=0.0, verbose_name='员工I分数')),
                ('workert', models.FloatField(default=0.0, verbose_name='测试员工4分数')),
            ],
        ),
        migrations.CreateModel(
            name='Responsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('workeru', models.FloatField(default=0.0, verbose_name='测试员工10分数')),
                ('workera', models.FloatField(default=0.0, verbose_name='测试员工12分数')),
                ('workerx', models.FloatField(default=0.0, verbose_name='测试员工15分数')),
                ('workerk', models.FloatField(default=0.0, verbose_name='员工K分数')),
                ('workerd', models.FloatField(default=0.0, verbose_name='员工D分数')),
                ('workerr', models.FloatField(default=0.0, verbose_name='员工R分数')),
                ('workerh', models.FloatField(default=0.0, verbose_name='测试员工16分数')),
                ('workerj', models.FloatField(default=0.0, verbose_name='测试员工9分数')),
                ('workern', models.FloatField(default=0.0, verbose_name='测试员工2分数')),
                ('workerl', models.FloatField(default=0.0, verbose_name='员工L分数')),
                ('workerb', models.FloatField(default=0.0, verbose_name='测试员工13分数')),
                ('workers', models.FloatField(default=0.0, verbose_name='员工S分数')),
                ('workerw', models.FloatField(default=0.0, verbose_name='员工W分数')),
                ('workerm', models.FloatField(default=0.0, verbose_name='员工M分数')),
                ('workeri', models.FloatField(default=0.0, verbose_name='员工I分数')),
                ('workert', models.FloatField(default=0.0, verbose_name='测试员工4分数')),
            ],
        ),
        migrations.AlterModelOptions(
            name='attitude',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scores',
            options={'verbose_name': '总分排名', 'verbose_name_plural': '总分'},
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerd',
            field=models.FloatField(default=0.0, verbose_name='员工D分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerb',
            field=models.FloatField(default=0.0, verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerh',
            field=models.FloatField(default=0.0, verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workeri',
            field=models.FloatField(default=0.0, verbose_name='员工I分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerj',
            field=models.FloatField(default=0.0, verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerk',
            field=models.FloatField(default=0.0, verbose_name='员工K分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerl',
            field=models.FloatField(default=0.0, verbose_name='员工L分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerm',
            field=models.FloatField(default=0.0, verbose_name='员工M分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workern',
            field=models.FloatField(default=0.0, verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerr',
            field=models.FloatField(default=0.0, verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workers',
            field=models.FloatField(default=0.0, verbose_name='员工S分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workert',
            field=models.FloatField(default=0.0, verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerw',
            field=models.FloatField(default=0.0, verbose_name='员工W分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workerx',
            field=models.FloatField(default=0.0, verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='workera',
            field=models.FloatField(default=0.0, verbose_name='测试员工12分数'),
        ),
    ]
