# Generated by Django 2.1.2 on 2020-04-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_auto_20200407_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='suweiheng',
            field=models.FloatField(default=0.0, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='worker_name',
            field=models.CharField(editable=False, max_length=200, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='year_season',
            field=models.CharField(editable=False, max_length=200, verbose_name='年季度'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='suweiheng',
            field=models.FloatField(default=0.0, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='worker_name',
            field=models.CharField(editable=False, max_length=200, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='year_season',
            field=models.CharField(editable=False, max_length=200, verbose_name='年季度'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='suweiheng',
            field=models.FloatField(default=0.0, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='worker_name',
            field=models.CharField(editable=False, max_length=200, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='year_season',
            field=models.CharField(editable=False, max_length=200, verbose_name='年季度'),
        ),
    ]
