# Generated by Django 2.1.2 on 2020-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20200408_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='at_changxiaobo',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='常晓波分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_huangqiangxu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='黄锵栩分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_liufeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘峰分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_liujiang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘江分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_liulei',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘雷分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_yangxiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='杨晓分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='张晨分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_changxiaobo',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='常晓波分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_huangqiangxu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='黄锵栩分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_liufeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘峰分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_liujiang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘江分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_liulei',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘雷分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_yangxiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='杨晓分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='张晨分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_changxiaobo',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='常晓波分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_huangqiangxu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='黄锵栩分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_liufeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘峰分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_liujiang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘江分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_liulei',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='刘雷分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_yangxiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='杨晓分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='张晨分数'),
        ),
    ]
