# Generated by Django 2.1.2 on 2020-04-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_auto_20200408_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='at_workerd',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工D分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workeri',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工I分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerk',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工K分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerl',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工L分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerm',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工M分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerw',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工W分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工12分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerd',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工D分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workeri',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工I分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerk',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工K分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerl',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工L分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerm',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工M分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workeru',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工10分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerw',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工W分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工12分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerd',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工D分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workeri',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工I分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerk',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工K分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerl',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工L分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerm',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工M分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workeru',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工10分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerw',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='员工W分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (83, 83), (79, 79)], verbose_name='测试员工12分数'),
        ),
    ]
