# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20200408_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attitude',
            name='at_workerd',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_workeri',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_workerk',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_workerl',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_workerm',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_workerw',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workerd',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workeri',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workerk',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workerl',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workerm',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_workerw',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workerd',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workeri',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workerk',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workerl',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workerm',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_workerw',
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workere',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工8分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workerc',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工14分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workero',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工7分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workerp',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工11分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workerq',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工1数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_workerv',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工6分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workere',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工8分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workerc',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工14分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workero',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工7分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workerp',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工11分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workerq',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工1数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_workerv',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工6分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workere',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工8分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workerc',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工14分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workero',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工7分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workerp',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工11分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workerq',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工1数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_workerv',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工6分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workeru',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工10分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工12分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workeru',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工10分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工12分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerb',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工13分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerh',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工16分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerj',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工9分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workern',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工2分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerr',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='员工R分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workers',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工5分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workert',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工4分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workeru',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工10分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerx',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工15分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workera',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='测试员工12分数'),
        ),
    ]
