# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_auto_20200408_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attitude',
            name='at_changxiaobo',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_huangqiangxu',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_liufeng',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_liujiang',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_liulei',
        ),
        migrations.RemoveField(
            model_name='attitude',
            name='at_yangxiao',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_changxiaobo',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_huangqiangxu',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_liufeng',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_liujiang',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_liulei',
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='di_yangxiao',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_changxiaobo',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_huangqiangxu',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_liufeng',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_liujiang',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_liulei',
        ),
        migrations.RemoveField(
            model_name='responsibility',
            name='re_yangxiao',
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_chenjunbiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈浚标分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_huangmingxian',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='黄铭贤分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_lutianyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陆天洋分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_mamengyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='马梦阳分数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_pengjunlin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='彭俊霖数'),
        ),
        migrations.AddField(
            model_name='attitude',
            name='at_xuhaipeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='许海鹏分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_chenjunbiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈浚标分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_huangmingxian',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='黄铭贤分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_lutianyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陆天洋分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_mamengyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='马梦阳分数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_pengjunlin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='彭俊霖数'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='di_xuhaipeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='许海鹏分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_chenjunbiao',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈浚标分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_huangmingxian',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='黄铭贤分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_lutianyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陆天洋分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_mamengyang',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='马梦阳分数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_pengjunlin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='彭俊霖数'),
        ),
        migrations.AddField(
            model_name='responsibility',
            name='re_xuhaipeng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='许海鹏分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='张晨分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='张晨分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_chenlidong',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='陈立栋分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_guoshaochuan',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='郭少钏分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_huoxiaoge',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='霍晓歌分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_lixiaoxin',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='李晓昕分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_suju',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏飓分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_suweiheng',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='苏伟衡分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_wangzhiwu',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='汪志武分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_weiguorui',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='韦国锐分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_yuqiusi',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='于秋思分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_zhangchen',
            field=models.IntegerField(choices=[(95, 95), (91, 91), (87, 87), (83, 83), (79, 79)], default=95, verbose_name='张晨分数'),
        ),
    ]
