# Generated by Django 4.2 on 2024-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0008_auto_20221013_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attitude',
            name='at_workere',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工E分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerb',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工B分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerh',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工H分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerc',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工C分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerj',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工J分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workern',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工N分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workero',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工O分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerp',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工P分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerq',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工Q数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerr',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工F分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workers',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工S分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workert',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工T分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workeru',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工U分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerv',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工V分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workerx',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工X分数'),
        ),
        migrations.AlterField(
            model_name='attitude',
            name='at_workera',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工A分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workere',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工E分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerb',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工B分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerh',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工H分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerc',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工C分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerj',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工J分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workern',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工N分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workero',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工O分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerp',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工P分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerq',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工Q数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerr',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工F分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workers',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工S分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workert',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工T分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workeru',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工U分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerv',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工V分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workerx',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工X分数'),
        ),
        migrations.AlterField(
            model_name='discipline',
            name='di_workera',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工A分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workere',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工E分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerb',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工B分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerh',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工H分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerc',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工C分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerj',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工J分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workern',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工N分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workero',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工O分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerp',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工P分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerq',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工Q数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerr',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工F分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workers',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工S分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workert',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工T分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workeru',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工U分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerv',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工V分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workerx',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工X分数'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='re_workera',
            field=models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='员工A分数'),
        ),
    ]
