# Generated by Django 4.2.30 on 2026-06-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_alter_attitude_at_chenjunbiao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attitude',
            old_name='at_suju',
            new_name='at_fanyf53',
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='di_suju',
            new_name='di_fanyf53',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='re_suju',
            new_name='re_fanyf53',
        ),
    ]
