# Generated by Django 4.2.30 on 2026-06-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0009_alter_rating_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attitude',
            old_name='at_workerr',
            new_name='at_workerf',
        ),
        migrations.RenameField(
            model_name='discipline',
            old_name='di_workerr',
            new_name='di_workerf',
        ),
        migrations.RenameField(
            model_name='responsibility',
            old_name='re_workerr',
            new_name='re_workerf',
        ),
    ]
