# Generated by Django 4.2.30 on 2026-06-11 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scores', '0010_rename_rating_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemocracyRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_season', models.CharField(max_length=200, verbose_name='年季度')),
                ('attitude', models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='工作态度')),
                ('responsibility', models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='责任心')),
                ('discipline', models.IntegerField(choices=[(100, 100), (90, 90), (80, 80), (70, 70), (60, 60), (50, 50), (40, 40), (30, 30), (20, 20), (10, 10), (0, 0)], default=100, verbose_name='工作纪律')),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='democracy_given', to=settings.AUTH_USER_MODEL, verbose_name='测评人')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='democracy_received', to=settings.AUTH_USER_MODEL, verbose_name='被测评人')),
            ],
            options={
                'verbose_name': '民主测评',
                'verbose_name_plural': '民主测评',
                'unique_together': {('evaluator', 'target', 'year_season')},
            },
        ),
        migrations.DeleteModel(
            name='Attitude',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Responsibility',
        ),
    ]
