# Generated by Django 5.2.15 on 2026-06-29 17:15

import django.db.models.deletion
from django.db import migrations, models


def create_default_formula_policy(apps, schema_editor):
    ScoreFormulaPolicy = apps.get_model('scores', 'ScoreFormulaPolicy')
    ScoreFormulaPolicy.objects.get_or_create(
        name='当前兼容公式',
        effective_year=2000,
        effective_month=1,
        defaults={
            'ranking_formula': 'legacy_cap40',
            'is_active': True,
            'notes': '系统默认兼容公式：项目和特殊加分不压缩，工单/割接/故障/日常合计封顶40。',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_democracyrating_delete_attitude_delete_discipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreFormulaPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='公式名称')),
                ('effective_year', models.PositiveIntegerField(verbose_name='生效年份')),
                ('effective_month', models.PositiveSmallIntegerField(verbose_name='生效月份')),
                ('ranking_formula', models.CharField(choices=[('legacy_cap40', '兼容公式：工单/割接/故障/日常封顶40'), ('compressed_sum', '分类压缩求和'), ('raw_sum', '不压缩直接求和')], default='legacy_cap40', max_length=30, verbose_name='排名公式')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '绩效公式',
                'verbose_name_plural': '绩效公式',
                'ordering': ['-effective_year', '-effective_month', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreCategoryRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('posts', '项目类'), ('orders', '工单类'), ('cutovers', '割接类'), ('bonuses', '特殊加分项'), ('routine', '日常工作'), ('faulty', '故障处理')], max_length=20, verbose_name='工作类别')),
                ('algorithm', models.CharField(choices=[('none', '不压缩'), ('exponential', '越多加分越少'), ('hard_cap', '硬封顶')], default='none', max_length=20, verbose_name='算法')),
                ('cap', models.FloatField(default=0, verbose_name='上限/逼近值')),
                ('lambda_value', models.FloatField(default=0, verbose_name='压缩系数')),
                ('weight', models.FloatField(default=1, verbose_name='权重')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to='scores.scoreformulapolicy', verbose_name='所属公式')),
            ],
            options={
                'verbose_name': '分类算法参数',
                'verbose_name_plural': '分类算法参数',
                'ordering': ['policy', 'category'],
                'unique_together': {('policy', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ScoreRankingSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('score_year', models.PositiveIntegerField(verbose_name='年份')),
                ('score_month', models.PositiveSmallIntegerField(verbose_name='月份')),
                ('raw_posts', models.FloatField(default=0, verbose_name='原始项目分数')),
                ('raw_orders', models.FloatField(default=0, verbose_name='原始工单分数')),
                ('raw_cutovers', models.FloatField(default=0, verbose_name='原始割接分数')),
                ('raw_bonuses', models.FloatField(default=0, verbose_name='原始特殊加分')),
                ('raw_faulty', models.FloatField(default=0, verbose_name='原始故障分数')),
                ('raw_routine', models.FloatField(default=0, verbose_name='原始日常分数')),
                ('final_posts', models.FloatField(default=0, verbose_name='公式后项目分数')),
                ('final_orders', models.FloatField(default=0, verbose_name='公式后工单分数')),
                ('final_cutovers', models.FloatField(default=0, verbose_name='公式后割接分数')),
                ('final_bonuses', models.FloatField(default=0, verbose_name='公式后特殊加分')),
                ('final_faulty', models.FloatField(default=0, verbose_name='公式后故障分数')),
                ('final_routine', models.FloatField(default=0, verbose_name='公式后日常分数')),
                ('work_score', models.FloatField(default=0, verbose_name='工作绩效分')),
                ('democracy_score', models.FloatField(default=0, verbose_name='民主测评分')),
                ('total_score', models.FloatField(default=0, verbose_name='总分')),
                ('rank', models.PositiveIntegerField(default=0, verbose_name='排名')),
                ('policy_snapshot', models.JSONField(blank=True, default=dict, verbose_name='公式快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_snapshots', to='scores.scoreformulapolicy', verbose_name='使用公式')),
            ],
            options={
                'verbose_name': '月度排名快照',
                'verbose_name_plural': '月度排名快照',
                'ordering': ['score_year', 'score_month', 'rank', 'worker_name'],
                'unique_together': {('worker_name', 'score_year', 'score_month')},
            },
        ),
        migrations.RunPython(create_default_formula_policy, migrations.RunPython.noop),
    ]
