# Generated by Django 2.1.2 on 2018-12-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='pj_score',
            field=models.IntegerField(default=1, verbose_name='加分'),
        ),
    ]
