# Generated by Django 2.1.2 on 2019-04-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0002_auto_20181225_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='faulty',
            name='pj_type',
            field=models.CharField(choices=[('硬件', '硬件'), ('投诉', '投诉'), ('软件', '软件'), ('其他', '其他')], default='硬件', max_length=200, verbose_name='故障类型'),
        ),
    ]
