# Generated by Django 2.1.2 on 2019-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0003_faulty_pj_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='pj_leader',
            field=models.CharField(choices=[('陈立栋', '陈立栋'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('郭少钏', '郭少钏'), ('于秋思', '于秋思'), ('苏飓', '苏飓'), ('苏伟衡', '苏伟衡'), ('杨晓', '杨晓'), ('霍晓歌', '霍晓歌'), ('李晓昕', '李晓昕'), ('张晨', '张晨')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('陈立栋', '陈立栋'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('郭少钏', '郭少钏'), ('于秋思', '于秋思'), ('苏飓', '苏飓'), ('苏伟衡', '苏伟衡'), ('杨晓', '杨晓'), ('霍晓歌', '霍晓歌'), ('李晓昕', '李晓昕'), ('张晨', '张晨')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('陈立栋', '陈立栋'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('郭少钏', '郭少钏'), ('于秋思', '于秋思'), ('苏飓', '苏飓'), ('苏伟衡', '苏伟衡'), ('杨晓', '杨晓'), ('霍晓歌', '霍晓歌'), ('李晓昕', '李晓昕'), ('张晨', '张晨')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('陈立栋', '陈立栋'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('郭少钏', '郭少钏'), ('于秋思', '于秋思'), ('苏飓', '苏飓'), ('苏伟衡', '苏伟衡'), ('杨晓', '杨晓'), ('霍晓歌', '霍晓歌'), ('李晓昕', '李晓昕'), ('张晨', '张晨')], max_length=200, verbose_name='完成人员4'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_score',
            field=models.IntegerField(choices=[(1, 1), (2, 2)], default=1, verbose_name='加分'),
        ),
    ]
