# Generated by Django 2.1.2 on 2019-12-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0004_auto_20191222_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='faulty',
            name='pj_manufacturer',
            field=models.CharField(choices=[('华为', '华为'), ('中兴', '中兴'), ('思科', '思科'), ('神州数码', '神州数码'), ('恒安嘉新', '恒安嘉新'), ('其他', '其他')], default='华为', max_length=200, verbose_name='故障类型'),
        ),
    ]
