# Generated by Django 2.1.2 on 2019-12-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0005_faulty_pj_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='pj_manufacturer',
            field=models.CharField(choices=[('华为', '华为'), ('中兴', '中兴'), ('思科', '思科'), ('神州数码', '神州数码'), ('恒安嘉新', '恒安嘉新'), ('其他', '其他')], default='华为', max_length=200, verbose_name='厂家'),
        ),
    ]
