# Generated by Django 2.1.2 on 2020-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0006_auto_20191228_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='pj_type',
            field=models.CharField(choices=[('硬件', '硬件'), ('软件', '软件'), ('其他', '其他')], default='硬件', max_length=200, verbose_name='故障类型'),
        ),
    ]
