# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faulty', '0007_auto_20200406_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faulty',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_manufacturer',
            field=models.CharField(choices=[('华为', '华为'), ('中兴', '中兴'), ('诺基亚', '诺基亚'), ('思科', '思科'), ('神州数码', '神州数码'), ('恒安嘉新', '恒安嘉新'), ('其他', '其他')], default='华为', max_length=200, verbose_name='厂家'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员4'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1, verbose_name='加分'),
        ),
        migrations.AlterField(
            model_name='faulty',
            name='pj_type',
            field=models.CharField(choices=[('硬件', '硬件'), ('软件', '软件'), ('投诉', '投诉'), ('其他', '其他')], default='硬件', max_length=200, verbose_name='故障类型'),
        ),
    ]
