# Generated by Django 2.1.2 on 2018-11-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutovers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutover_num', models.CharField(max_length=200, verbose_name='割接工单编号')),
                ('title', models.CharField(max_length=200, verbose_name='割接名称')),
                ('pj_leader', models.CharField(max_length=200, verbose_name='割接负责人')),
                ('deadline_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='割接日期')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('body', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'Cutovers',
            },
        ),
    ]
