# Generated by Django 2.1.2 on 2018-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutovers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cutovers',
            options={'verbose_name': '割接', 'verbose_name_plural': '割接'},
        ),
    ]
