# Generated by Django 2.1.2 on 2019-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutovers', '0004_auto_20181225_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutovers',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('员工D', '员工D'), ('员工L', '员工L'), ('员工M', '员工M'), ('员工K', '员工K'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('员工W', '员工W'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='割接负责人'),
        ),
    ]
