# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutovers', '0005_auto_20191222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutovers',
            name='body',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cutovers',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='割接负责人'),
        ),
    ]
