# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutovers', '0005_auto_20191222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutovers',
            name='body',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='cutovers',
            name='pj_leader',
            field=models.CharField(choices=[('陈立栋', '陈立栋'), ('陈浚标', '陈浚标'), ('黄铭贤', '黄铭贤'), ('陆天洋', '陆天洋'), ('许海鹏', '许海鹏'), ('马梦阳', '马梦阳'), ('郭少钏', '郭少钏'), ('于秋思', '于秋思'), ('苏飓', '苏飓'), ('苏伟衡', '苏伟衡'), ('彭俊霖', '彭俊霖'), ('霍晓歌', '霍晓歌'), ('李晓昕', '李晓昕'), ('张晨', '张晨'), ('汪志武', '汪志武')], max_length=200, verbose_name='割接负责人'),
        ),
    ]
