# Generated by Django 4.2.30 on 2026-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutovers', '0007_alter_cutovers_pj_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutovers',
            name='pj_leader',
            field=models.CharField(max_length=200, verbose_name='割接负责人'),
        ),
    ]
