# Generated by Django 2.1.2 on 2019-12-22 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True, verbose_name='网站')),
                ('portfolio_phone', models.BigIntegerField(verbose_name='电话号码')),
                ('portfolio_job_type', models.CharField(choices=[('物联网', '物联网'), ('公众', '公众'), ('数通', '数通'), ('其他', '其他')], max_length=50, verbose_name='工作类型')),
                ('portfolio_descption', models.TextField(verbose_name='个人介绍')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics', verbose_name='照片')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
