# Generated by Django 2.1.2 on 2019-12-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_job_type',
            new_name='profile_job_type',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='profile_site',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_descption',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_phone',
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_descption',
            field=models.TextField(blank=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='profile_phone',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='电话号码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pic', verbose_name='照片'),
        ),
    ]
