# Generated by Django 4.2.30 on 2026-06-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200408_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=120, verbose_name='标题')),
                ('subtitle', models.CharField(blank=True, default='', max_length=240, verbose_name='副标题')),
                ('image', models.ImageField(upload_to='home_slides', verbose_name='轮播图片')),
                ('link', models.URLField(blank=True, default='', verbose_name='链接')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '首页轮播图',
                'verbose_name_plural': '首页轮播图',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='人力考核系统', max_length=100, verbose_name='项目名称')),
                ('footer_text', models.CharField(default='运维', max_length=100, verbose_name='页脚名称')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
            },
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='账号已审批'),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('employee', '普通员工'), ('approver', '审批人'), ('manager', '管理员')], default='employee', max_length=20, verbose_name='角色'),
        ),
    ]
