# Generated by Django 4.2.30 on 2026-06-11 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_homeslide_sitesetting_userprofileinfo_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('orders', '工单'), ('cutovers', '割接'), ('posts', '项目'), ('routine', '日常工作'), ('faulty', '故障处理'), ('bonuses', '特殊加分')], max_length=20, verbose_name='申请类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('score', models.FloatField(default=0, verbose_name='申请分数')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('evidence', models.FileField(blank=True, upload_to='work_evidence', verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='审批意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_applications', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_work_applications', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '工作量申请',
                'verbose_name_plural': '工作量申请',
                'ordering': ['-created_at'],
            },
        ),
    ]
