# Generated by Django 4.2.30 on 2026-06-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_workapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplication',
            name='work_date',
            field=models.DateField(blank=True, null=True, verbose_name='相关日期'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='work_manufacturer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='厂家'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='work_num',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='work_progress',
            field=models.FloatField(blank=True, null=True, verbose_name='当前进度'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='work_subtype',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='子类型'),
        ),
    ]
