# Generated by Django 4.2.30 on 2026-06-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_workapplication_type_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, upload_to='site_logo', verbose_name='导航栏Logo'),
        ),
    ]
