# Generated by Django 4.2.30 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='scores_announcement',
            field=models.TextField(blank=True, default='', verbose_name='考核原则公告（支持HTML）'),
        ),
    ]
