# Generated by Django 5.2.15 on 2026-06-12 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sitesetting_scores_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplication',
            name='materialized_model',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='生成业务表'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='materialized_object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='生成业务ID'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='pj_participant1',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='pj_participant2',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='pj_participant3',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='完成人员4'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='workload_allot',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='比例1'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='workload_allot1',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='比例2'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='workload_allot2',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='比例3'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='workload_allot3',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='比例4'),
        ),
    ]
