# Generated by Django 5.2.15 on 2026-06-29 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_workapplication_materialized_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workapplication',
            name='duplicate_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='重复检查时间'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='duplicate_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_overridden_work_applications', to=settings.AUTH_USER_MODEL, verbose_name='重复确认人'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='duplicate_override_reason',
            field=models.TextField(blank=True, default='', verbose_name='重复审批确认原因'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='duplicate_signature',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='重复识别签名'),
        ),
        migrations.AddField(
            model_name='workapplication',
            name='duplicate_status',
            field=models.CharField(choices=[('none', '未发现重复'), ('suspected', '疑似重复'), ('confirmed_duplicate', '确认重复'), ('overridden', '已确认通过')], default='none', max_length=30, verbose_name='重复状态'),
        ),
    ]
