"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 2.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

TEMPLATE_DIR = os.path.join(BASE_DIR,'templates')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*#2m()bwk*vod$kf&2%a79bq2%&26515^i2#$8-lq57=5z1=-9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["192.168.50.69","127.0.0.1","10.116.1.121","localhost"]


# Application definition

INSTALLED_APPS = [
    # Vue.js + Element-UI 后台主题，必须放在 django.contrib.admin 之前
    'simpleui',
    'scores.apps.ScoresConfig',
    'posts.apps.PostsConfig',
    'bonuses.apps.BonusesConfig',
    'cutovers.apps.CutoversConfig',
    'orders.apps.OrdersConfig',
    'faulty.apps.FaultyConfig',
    'routine.apps.RoutineConfig',
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR,],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.site_settings',
                'accounts.context_processors.approval_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'workstaff',
        'USER':'root',
        'PASSWORD':'root',
        'HOST':'localhost',
        'PORT':''
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/


STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'myproject/static'),

]

# Media Folders settings
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Messages
from django.contrib.messages import constants as messages
MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# ---- SimpleUI：基于 Vue.js + Element-UI 的后台管理主题 ----
# 内网部署，静态资源全部走本地，不依赖外网 CDN
SIMPLEUI_STATIC_OFFLINE = True
# 关闭使用统计上报与首页的 simpleui 仓库信息卡片
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_INFO = False
# 默认主题（登录后右上角“头像 -> 更换主题”可随时切换）
SIMPLEUI_DEFAULT_THEME = 'e-blue-pro.css'
# 后台首页标题与图标
SIMPLEUI_HOME_TITLE = '人力考核系统'
SIMPLEUI_HOME_ICON = 'fas fa-chart-line'
# 左侧菜单图标（按 app verbose_name / model verbose_name 匹配）
SIMPLEUI_ICON = {
    '账号与系统': 'fas fa-cogs',
    '考核分数': 'fas fa-trophy',
    '工单类': 'fas fa-clipboard-list',
    '项目类': 'fas fa-project-diagram',
    '割接类': 'fas fa-network-wired',
    '特殊加分项': 'fas fa-star',
    '故障类': 'fas fa-bug',
    '日常类': 'fas fa-calendar-check',
    '认证和授权': 'fas fa-user-shield',
    '总分': 'fas fa-trophy',
    '民主测评': 'fas fa-vote-yea',
    '工作量申请': 'fas fa-file-signature',
    '系统设置': 'fas fa-sliders-h',
    '首页轮播图': 'fas fa-images',
    '工单': 'fas fa-clipboard-list',
    '项目': 'fas fa-project-diagram',
    '割接': 'fas fa-network-wired',
    '特殊加分': 'fas fa-star',
    '故障处理': 'fas fa-wrench',
    '日常工作': 'fas fa-calendar-check',
    '用户': 'fas fa-user',
    '组': 'fas fa-users',
}



try:
    from .local_settings import *
except ImportError:
    pass

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

