# Generated by Django 2.1.2 on 2018-11-18 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bonuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='加分项目名称')),
                ('pj_score', models.IntegerField(default=0, verbose_name='项目加分')),
                ('pj_leader', models.CharField(max_length=200, verbose_name='项目负责人')),
                ('workload_allot', models.FloatField(default=0.0, verbose_name='比例')),
                ('pj_participant1', models.CharField(blank=True, max_length=200, verbose_name='完成人员1')),
                ('workload_allot1', models.FloatField(default=0.0, verbose_name='比例1')),
                ('pj_participant2', models.CharField(blank=True, max_length=200, verbose_name='完成人员2')),
                ('workload_allot2', models.FloatField(default=0.0, verbose_name='比例2')),
                ('pj_participant3', models.CharField(blank=True, max_length=200, verbose_name='完成人员3')),
                ('workload_allot3', models.FloatField(default=0.0, verbose_name='比例3')),
                ('is_delayed', models.BooleanField(default=False, verbose_name='是否已经在别处加分')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='开始日期')),
                ('body', models.TextField(blank=True, default='', verbose_name='备注')),
            ],
            options={
                'verbose_name_plural': 'Bonuses',
            },
        ),
    ]
