# Generated by Django 2.1.2 on 2018-11-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuses',
            options={'verbose_name': '特殊加分', 'verbose_name_plural': '特殊加分'},
        ),
    ]
