# Generated by Django 2.1.2 on 2019-12-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0004_auto_20181225_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('苏飓', '苏飓'), ('测试员工5', '测试员工5'), ('杨晓', '杨晓'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('苏飓', '苏飓'), ('测试员工5', '测试员工5'), ('杨晓', '杨晓'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('苏飓', '苏飓'), ('测试员工5', '测试员工5'), ('杨晓', '杨晓'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('常晓波', '常晓波'), ('刘江', '刘江'), ('刘雷', '刘雷'), ('刘峰', '刘峰'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('苏飓', '苏飓'), ('测试员工5', '测试员工5'), ('杨晓', '杨晓'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员4'),
        ),
    ]
