# Generated by Django 4.2.30 on 2026-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonuses', '0007_alter_bonuses_pj_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuses',
            name='pj_leader',
            field=models.CharField(max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant1',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant2',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='bonuses',
            name='pj_participant3',
            field=models.CharField(blank=True, max_length=200, verbose_name='完成人员4'),
        ),
    ]
