# Generated by Django 2.1.2 on 2018-11-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': '工单', 'verbose_name_plural': '工单'},
        ),
        migrations.AddField(
            model_name='orders',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
        ),
        migrations.AddField(
            model_name='orders',
            name='orders_type',
            field=models.CharField(choices=[('行业', '行业'), ('物联网', '物联网'), ('内容计费', '内容计费'), ('DNS', 'DNS'), ('PCRF', 'PCRF'), ('其他', '其他')], default='物联网', max_length=24, verbose_name='工单类型:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_leader',
            field=models.CharField(max_length=200, verbose_name='负责人'),
        ),
    ]
