# Generated by Django 2.1.2 on 2018-12-18 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20181118_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_delayed',
        ),
        migrations.AddField(
            model_name='orders',
            name='is_not_delayed',
            field=models.BooleanField(default=True, verbose_name='未超时'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='完成'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_type',
            field=models.CharField(choices=[('行业', '行业'), ('物联网', '物联网'), ('内容计费', '内容计费'), ('DNS', 'DNS'), ('PCRF', 'PCRF'), ('国际漫游', '国际漫游'), ('SGSN/MME局数据', 'SGSN/MME局数据'), ('SGW/PGW局数据', 'SGW/PGW局数据'), ('其他', '其他')], default='物联网', max_length=24, verbose_name='工单类型:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('员工D', '员工D'), ('员工L', '员工L'), ('员工M', '员工M'), ('员工K', '员工K'), ('员工G', '员工G'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('员工W', '员工W'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工10', '测试员工10'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('员工D', '员工D'), ('员工L', '员工L'), ('员工M', '员工M'), ('员工K', '员工K'), ('员工G', '员工G'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('员工W', '员工W'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工10', '测试员工10'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('员工D', '员工D'), ('员工L', '员工L'), ('员工M', '员工M'), ('员工K', '员工K'), ('员工G', '员工G'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('员工W', '员工W'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工10', '测试员工10'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('员工D', '员工D'), ('员工L', '员工L'), ('员工M', '员工M'), ('员工K', '员工K'), ('员工G', '员工G'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('员工W', '员工W'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工10', '测试员工10'), ('测试员工12', '测试员工12')], max_length=200, verbose_name='完成人员4'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='workload_allot',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='比例1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='workload_allot1',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='比例2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='workload_allot2',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='比例3'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='workload_allot3',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1)], verbose_name='比例4'),
        ),
    ]
