# Generated by Django 2.1.2 on 2018-12-25 14:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181218_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='deadline_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='工单到期日期'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_score',
            field=models.IntegerField(default=1, verbose_name='工单加分'),
        ),
    ]
