# Generated by Django 2.1.2 on 2022-10-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191222_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='body',
            field=models.TextField(default='', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_type',
            field=models.CharField(choices=[('行业', '行业'), ('物联网', '物联网'), ('内容计费', '内容计费'), ('DNS', 'DNS'), ('PCRF/PCF', 'PCRF/PCF'), ('国际漫游', '国际漫游'), ('SGSN/MME局数据', 'SGSN/MME局数据'), ('SGW/PGW局数据', 'SGW/PGW局数据'), ('AMF', 'AMF'), ('SMF', 'SMF'), ('NRF', 'NRF'), ('UPF', 'UPF'), ('数通', '数通'), ('网管', '网管'), ('I层', 'I层'), ('其他', '其他')], default='物联网', max_length=24, verbose_name='工单类型:'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_leader',
            field=models.CharField(choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('测试员工13', '测试员工13'), ('测试员工8', '测试员工8'), ('测试员工14', '测试员工14'), ('测试员工7', '测试员工7'), ('测试员工6', '测试员工6'), ('测试员工11', '测试员工11'), ('测试员工16', '测试员工16'), ('测试员工15', '测试员工15'), ('员工R', '员工R'), ('测试员工5', '测试员工5'), ('测试员工1', '测试员工1'), ('测试员工9', '测试员工9'), ('测试员工2', '测试员工2'), ('测试员工12', '测试员工12'), ('测试员工4', '测试员工4')], max_length=200, verbose_name='完成人员4'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_score',
            field=models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='工单加分'),
        ),
    ]
