# Generated by Django 4.2 on 2024-03-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20221013_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='pj_leader',
            field=models.CharField(choices=[('员工B', '员工B'), ('员工E', '员工E'), ('员工C', '员工C'), ('员工O', '员工O'), ('员工V', '员工V'), ('员工P', '员工P'), ('员工H', '员工H'), ('员工X', '员工X'), ('员工F', '员工F'), ('员工S', '员工S'), ('员工Q', '员工Q'), ('员工J', '员工J'), ('员工N', '员工N'), ('员工A', '员工A'), ('员工T', '员工T')], max_length=200, verbose_name='完成人员1'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant1',
            field=models.CharField(blank=True, choices=[('员工B', '员工B'), ('员工E', '员工E'), ('员工C', '员工C'), ('员工O', '员工O'), ('员工V', '员工V'), ('员工P', '员工P'), ('员工H', '员工H'), ('员工X', '员工X'), ('员工F', '员工F'), ('员工S', '员工S'), ('员工Q', '员工Q'), ('员工J', '员工J'), ('员工N', '员工N'), ('员工A', '员工A'), ('员工T', '员工T')], max_length=200, verbose_name='完成人员2'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant2',
            field=models.CharField(blank=True, choices=[('员工B', '员工B'), ('员工E', '员工E'), ('员工C', '员工C'), ('员工O', '员工O'), ('员工V', '员工V'), ('员工P', '员工P'), ('员工H', '员工H'), ('员工X', '员工X'), ('员工F', '员工F'), ('员工S', '员工S'), ('员工Q', '员工Q'), ('员工J', '员工J'), ('员工N', '员工N'), ('员工A', '员工A'), ('员工T', '员工T')], max_length=200, verbose_name='完成人员3'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='pj_participant3',
            field=models.CharField(blank=True, choices=[('员工B', '员工B'), ('员工E', '员工E'), ('员工C', '员工C'), ('员工O', '员工O'), ('员工V', '员工V'), ('员工P', '员工P'), ('员工H', '员工H'), ('员工X', '员工X'), ('员工F', '员工F'), ('员工S', '员工S'), ('员工Q', '员工Q'), ('员工J', '员工J'), ('员工N', '员工N'), ('员工A', '员工A'), ('员工T', '员工T')], max_length=200, verbose_name='完成人员4'),
        ),
    ]
